### ISSUE TITLE
3) Routing use case 2 for OD pairs (more OD pairs, routed less often)

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#10]
- Every Tuesday: 08.30, 13.00, 17.00 (=3 queries)
	- Every Saturday: 13.00 (=1 query)
	-This will only run in selected months. One option would be to pre-program which months it will run in. Alternatively I can do some mass disabling, as long as use case 1 and 2 are distinguished in the data structure so I can target use case 2 only
	- Always route by mode = driving.  **Also route by mode = walking and mode = cycling if day of month** <=7 (i.e. do walking and cycling just the first Tuesday+Saturday of the month).
	-
	- These will be different sets of OD pairs to those in use case 1.  It would be nice if the two use cases could EITHER be kept completely distinct, with separate runs and journeys tables for each ; OR for you to add in a field that specifies usecase , and can take values 1 and 2.

**Comment by nikolai-b** [comment]
I've altered the Tue infrequent running to be at 08:30 and 17:30 (as it is easier if they run at the same minuet) instead of 08:30 and 17:00.  08:15 and 17:15 would be fine, let me know if that is a problem

**Comment by nikolai-b** [comment]
I've also added `mode` to `runs` so you can differentiate between the `driving`, `cycling` and `walking` routing.

**Comment by AnnaGoodman1** [comment]
> 
> 
> I've altered the Tue infrequent running to be at 08:30 and 17:30 (as it is easier if they run at the same minuet) instead of 08:30 and 17:00. 08:15 and 17:15 would be fine, let me know if that is a problem

Is this a typo? I asked for 08.30, 13.00, 17,30.... sp 08.30 and 17.30 not an alternation but perfect :) but if you are running other times could it be these, it makes it neater methodswise as one is at the exact midpoint time

**Comment by nikolai-b** [comment]
I've kept 13:00 unchanged but the others (8 & 17) are easier if they have they run at the same minute, e.g 15 or 30 (or 00)

**Comment by nikolai-b** [comment]
Right so as you mentioned we are already storing  the cycling and walking distances in the `distances` table.  This will happen for any journey that doesn't have a cycling and walking distance BUT it only happens once, not once per month.  
1. Are you wanting it to happen 4 times (Tue * 3 and Sat * 1) per month? I'm not sure the distances will change but I guess they might.
2. Do you want me to edit the code to only get the cycling and walking distances for `infrequently_routed` journeys or are you happy with `frequently_routed` journeys also having distances?

**Comment by AnnaGoodman1** [comment]
ok great. Though I need some help writing the SQL code to save for the distances file as a csv, for some reason I wasn't able to.

1. Hmm.  we don't expect them to change usually except I guess they might 1) if a new footpath or bridge is built, or 2) because Google changes its algoritm, or 3) Google routes bicycles differently during rush hour, e.g. to avoid busy sections – I'm not sure if it does this or not.  So I think ideally it would happen 4 times per month  (Tue * 3 and Sat * 1) , along with date and timestamp. Though NB only in the months where infrequently_routed journeys are happening.

2. It is not a big problem for all journeys to have the distances in there, but possibly a little better if only infrequently_routed . So change if easy, leave if not
