### ISSUE TITLE
ability to run routing at will

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#11]
it turns out you need to do quite a lot of testing to get the OD points right, as Google can be very fussy – e.g. if you put the point on the wrong side of a double carriageway it routes you on a long loop to get that correct side.  At the moment I've been doing the testing by making a version and then waiting until the next hour for it to be routed, then making edits and waiting again. But that won't be practical once journeys are being routed on Tuesdays only.  Could there be a mechanism where one forces an ad hoc routing (for all non-disabled trips) by typing something in the command line or somewhere?

**Comment by nikolai-b** [comment]
I've added `type` to journeys which can be:

[frequently_routed, infrequently_routed or test_routing](https://github.com/Active-Travel-Academy/ata-traffic-recorder/commit/b92dec25339a76f0065c7b2748d6279412ca89d2#diff-485b14fc79d6e090734184ba8382f3ad789623f0481ef859e1d10736be5e8666R23-R27)

I've set the default to be: `frequently_routed`, i.e. #9 

If you set it as `test_routing` then it will run within a minuet and be disabled after running.  You can update the `type` so if that works you can change the type to `infrequently_routed` or `frequently_routed`, and re-enable it.
