### ISSUE TITLE
bugs / questions

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#12]
- [x] waypoint
   - routes with a waypoint don't run, e.g. id= 3685

- [x] type
- Could the default become 'test_routing'
 - test_routing: the 'disabled after one run' feature isn't working, runs indefinitely.

- [ ] Mode
   - Is this automated such that the desired days and times run for walking/cycling automatically, rather than it needing manual setting? (hard to bug check as needs a first tuesday of the month!)

- [ ] Output
 I currently use the following code to get out data.  I would like type and mode added/merged into this output; and also it filtered not just  by ltn_id=4 but also where disabled=FALSE.  Could you adapt the code accordingly?
 
psql "select runs.time AT TIME ZONE 'Europe/London', ltns.scheme_name, journey_runs.* from journey_runs join runs on journey_runs.run_id = runs.id JOIN ltns ON runs.ltn_id = ltns.id WHERE ltn_id=4; " > "C:\Users\Anna\AnnaDesktop\test.csv"]

- [x] run_id
	- is this going up in increments of 5? any reason?

**Comment by nikolai-b** [comment]
I think these should be fixed now but I've not managed to update your SQL command.  I'll try tomorrow.

**Comment by AnnaGoodman1** [comment]
thanks, the ones ticked off below checked and are indeed working fine.

**Comment by AnnaGoodman1** [comment]
re mode: I forgot that you are already extracting the walking and cycling distances in 'distances'.  Actually the distance is all we need, not the journey time, if that makes it easier to build on 'distances' - i.e. we don't have to have duration.  And to check, this will happen automatically for these modes start of June?

**Comment by nikolai-b** [comment]
Something like this:

```
psql "select runs.time AT TIME ZONE 'Europe/London', ltns.scheme_name, journey_runs.*, journeys.type from journey_runs join runs on journey_runs.run_id = runs.id JOIN ltns ON runs.ltn_id = ltns.id JOIN journeys ON journeys.id = journey_runs.journey_id WHERE ltn_id=4 and journeys.disabled = FALSE; " > "C:\Users\Anna\AnnaDesktop\test.csv"]
```

but please only select things you need or you lose the benefit of the database, so add a `AND runs.time > '2021-05-20 06:00:00'` or something. Or `AND runs.id > LAST_ID_IN_YOUR_FILE`.
