### ISSUE TITLE
some journeys skipped

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#13]
There seems to be a bug where some journey sometimes get skipped.

I have repeatedly run this in psql

update journeys set disabled=FALSE where id>=5428 and id<=5471 ;

and the resulting journeys are enabled run once and then disabled (because there type is test_routing)

As per the table below, in some runs all 44 are run but in several some are skipped – not always the same ones each time.  Could you look into this?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Anna/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Anna/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Run | N runs / 44 | ones missiong
-- | -- | --
21208 | 44 |  
21209 | 44 |  
21210 | 44 |  
21211 | 44 |  
21212 | 41 | 5453,  5454,  5455
21213 | 40 | 5462,5463, 5464 , 5465
21214 | 44 |  
21215 | 43 | 5464

**Comment by AnnaGoodman1** [comment]
I noticed it most acutely in this set of multiple short journeys, made me wonder if there could be some sort of maximum requests per minute timeout.

**Comment by nikolai-b** [comment]
I don't see this:

```sql
select run_id, count(*) from journey_runs where run_id between 21208 and 21215 group by run_id;

 run_id | count 
--------+-------
  21208 |    44
  21209 |    44
  21210 |    44
  21211 |    44
  21212 |    44
  21213 |    44
  21214 |    44
  21215 |    44
```

**Comment by AnnaGoodman1** [comment]
Oh right sorry I see – those journeys are there I just couldn't see them in the export I did. That is because the csv files were sorted by column A and that was weirdly formatted so was not listing everything strictly chronologically
