### ISSUE TITLE
bug - journeys not running on time, infreq_routed not at all

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#15]
hi nikolai, just checking the Saturday runs and there seems to be a bug
 > frequently_routed: should have been on course to run x23, at 6.15, 6.45 etc- but instead has only run at 10.30
 > infrequently_routed : has not run at all

I also then tried to route a whole bunch of trips (in ltn_id=1) and now am getting the message, when I try to export them or login, 

psql: error: FATAL:  remaining connection slots are reserved for non-replication superuser connections

**Comment by nikolai-b** [comment]
Yes, something is taking all the available connections to our database.  I added 5e1a493d498ce061e2659555feb2eef66327e41b as I assumed it was us but now I'm not so sure.  I've restarted the database and I've now limited the number of connections our users can make:

```sql
alter user shared_role connection limit 5;
alter user r_program connection limit 5;
alter user asker connection limit 1;
```

so if it happens again I login with the superuser and work out what has happened.  Before even the superuser was getting that FATAL error so I couldn't find out what was going on.

**Comment by AnnaGoodman1** [comment]
ok great. might hab ebeen me hammering it with a huge test in ltn 1. but how about the times not being right? infrequently routed only at 13,00 (not x4), and frequently routed only x5 not x23?

**Comment by nikolai-b** [comment]
I'm not at home but was this about routing yesterday (Saturday) ? The bug above might have been the problem if it was.

**Comment by AnnaGoodman1** [comment]
yes, was about the routing on saturday. we can see what happens on Tuesday....
