### ISSUE TITLE
freq routed skipped on routing on sat

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#17]
select * from journey_runs where journey_id=5871 ;

misses out 11.30 aM (10.30 GMT)

**Comment by nikolai-b** [comment]
I think this might be the same issue as #15 when we were having:

```
psql: error: FATAL: remaining connection slots are reserved for non-replication superuser connections
```

I'm still not sure what was causing that.

**Comment by AnnaGoodman1** [comment]
sure. will check this saturday, but all looks fine today...
