### ISSUE TITLE
not routing walking/cycling

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#18]
Hi there, possibly there was a misunderstanding, I was expecting walking/cycling to run today for type='infrequently_routed' as it is Tues 1st June - but only driving is running  

try e.g. select * from runs where ltn_id=8 ;

If this could be fixed in time for Saturday then it would be ok to have it run just then, not today Tues as well. But I would like walking/cycling at least once

**Comment by nikolai-b** [comment]
I've manually routed them today, I don't think google does much time of the day so hopefully that is ok.  Should be fixed next month, you were very clear but the project isn't tested and turns out cron is more difficult that I'd estimated in doing this kind of stuff.
