### ISSUE TITLE
lines did not route??

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#19]
select * from runs where run_id> 21361;

 21424 |      9 | 2021-06-05 12:30:49.619118+00 | 2021-06-05 12:30:49.619118+00 | driving
 21425 |      7 | 2021-06-05 13:30:03.409788+00 | 2021-06-05 13:30:03.409788+00 | driving
 21426 |      9 | 2021-06-05 13:30:52.197492+00 | 2021-06-05 13:30:52.197492+00 | driving
 21427 |      7 | 2021-06-05 14:30:03.134359+00 | 2021-06-05 14:30:03.134359+00 | driving
 21428 |      9 | 2021-06-05 14:31:11.279451+00 | 2021-06-05 14:31:11.279451+00 | driving
 21429 |      8 | 2021-06-05 19:28:06.393643+00 | 2021-06-05 19:28:06.393643+00 | walking
 21430 |      9 | 2021-06-05 19:49:05.227434+00 | 2021-06-05 19:49:05.227434+00 | walking
 21431 |      8 | 2021-06-05 19:58:24.275517+00 | 2021-06-05 19:58:24.275517+00 | bicycling
 21432 |      9 | 2021-06-05 20:19:20.353425+00 | 2021-06-05 20:19:20.353425+00 | bicycling
 21434 |      7 | 2021-06-08 19:15:03.29567+00  | 2021-06-08 19:15:03.29567+00  | driving
 21435 |      9 | 2021-06-08 19:15:48.915601+00 | 2021-06-08 19:15:48.915601+00 | driving
 21436 |      7 | 2021-06-08 19:45:03.423638+00 | 2021-06-08 19:45:03.423638+00 | driving
 21437 |      9 | 2021-06-08 19:45:51.132891+00 | 2021-06-08 19:45:51.132891+00 | driving

>> I was expected that today,Tuesday, the frequently_routed lines would route 25 times, but instead only twice - at 19.15 and 19.45.  some bug introduced since last Tuesday, when it worked ok?  Really good if could be working for next Tuesday.

**Comment by nikolai-b** [comment]
I fixed it in https://github.com/Active-Travel-Academy/ata-traffic-recorder/commit/496f0eb0ab1e32524e35c0506f508b162314ef72 at 19:00+00 which explains why it worked at 19:15 and 19:45.  I introduced it [here](https://github.com/Active-Travel-Academy/ata-traffic-recorder/commit/81ad3681ca8245c08eea9272e5346bc4338e8275) when fixing the infrequent routes to only run in the first week of the month, sorry :weary:!
