### ISSUE TITLE
waypoints

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#7]
Hi @nikolai-b , I'm afraid we do need the waypoint functionality, sorry... A single waypoint would be enough. Anna

**Comment by AnnaGoodman1** [comment]
it would ideally be an optional field, as some journeys we actively want to specify and others we actively want not to specify

**Comment by nikolai-b** [comment]
I've seen this but haven't had a chance to do it yet :weary: .  I was planning on adding a 
`journeys.waypoint_1_lat, journeys.waypoint_1_lng` with some validation that if `1` was filled in the the other one must be.  Also I'm using 1 as I might just add 2 or 3 waypoints at the same time just in case as I don't think it is much harder to add a few and much easier to do it now than later :smile:

**Comment by AnnaGoodman1** [comment]
wonderful, thanks
