### ISSUE TITLE
2) Routing use case 1 for OD pairs (fewer OD pairs but routed more often)

### ISSUE THREAD

**Issue by AnnaGoodman1** [Active-Travel-Academy/ata-traffic-recorder#9]
- Do routing at the following times:
a.	Tuesday: 6.15, 6.45, 7.15, 7.45, 8.15, 8.45, 9.15, 9.45, 10.30, 11.30, 12.30, 13.30. 14.30, 15.30, 16.15. 16.45, 17.15, 17.45, 18.15, 18.45, 19.30, 20.00, 20.30 (=23 queries)
b.	Saturday: 10.30, 11.30, 12.30, 13.30. 14.30, 15.30 ( = 6 quieries)
	- This will run continuously
	- this will only route by mode = driving.

(this is like what we have now, but just Tues/Sat, and different times)

**Comment by AnnaGoodman1** [comment]
For Tuesdays, the timings of the frequently_routed trips are not quite right
15:15 and 15:45 - included but not needed
19.30, 20.00, 20.30 - missing

**Comment by nikolai-b** [comment]
Sorry, closed by mistake.  Could we do
> 19.15, 19:45, 20.15, 20.45

instead of

> 19:30, 20:00, 20:30

It makes it easier for me to manage to cron config so less likely to make mistakes

**Comment by AnnaGoodman1** [comment]
ys fine, thanks
